### ISSUE TITLE
Random error when generating image (says weight is unavailable but is not in the JSON)

### ISSUE THREAD

**Issue by guivr** [fofr/cog-comfyui#104] opened 2024-06-17 07:27 UTC
First, thank you so much for your work. This is great and really useful.

Unfortunately, I've been getting errors like:

`
ERROR Error: Prediction failed: iclight_sd15_fc.safetensors unavailable. View the list of available weights: https://github.com/fofr/cog-comfyui/blob/main/supported_weights.md
`

when generating images.

The name of the model/weight `iclight_sd15_fc.safetensors` is random, and sometimes shows `sdxl_vae_madebyollin.safetensors`, `kl-f8-anime2.ckpt`, or anything else.

These weights were never in my JSON, so I think they leak from other users.

Maybe there is a cache of some type when the model is still warm?

Turning on the current existing option to clean the cache is not working.

**Comment by guivr** [comment] 2024-06-17 13:11
Hi, fofr!

Here's the prediction link:
https://replicate.com/p/6gxjkymet9rgp0cg4s8v03xfsc

Once someone inputs any invalid .safetensors, the next generations for everyone that uses this cog will fail until the model sleeps (gets cold) again.

**Comment by fofr** [comment] 2024-06-17 14:23
Thanks this was caused by mutable default args in Python and fixed in 3bae2fa7f5f4cf06d8ce1f01b1bb404d599b1538
I've pushed a new model version to Replicate.

**Closed by fofr** 2024-06-17 14:23 UTC

**Comment by guivr** [comment] 2024-06-17 15:00
> Thanks this was caused by mutable default args in Python and fixed in [3bae2fa](https://github.com/fofr/cog-comfyui/commit/3bae2fa7f5f4cf06d8ce1f01b1bb404d599b1538) I've pushed a new model version to Replicate.

Thank you so much!
